default:
  http:
    port: 3000
  mailer:
    service: 'Gmail'
    user: 'username@gmail.com'
    password: 'password'
    fromUser: 'ME ✔ <username@gmail.com'
    toUserOK: 'username@gmail.com'
    toUserKO: 'username@gmail.com'
    sujectMailOK: ' Les indicateurs du {0} sont disponibles'
    sujectMailKO: ' Un problème a eu lieu lors de la mise à jour des indicateurs'
  cron:
    time: '0 23 * * * *'
  shell:
    dirFile: 'exemples'
    sftpServer: '<sftp_username>@<sftp_id>'
  seuil:
    indicateur3: '400'
    indicateur4: '400'
    indicateur5: '400'
    indicateur6: '35'
    indicateur7: '35'
    indicateur8: '35'
    indicateur9: '98%'
    indicateur10: '2%'
    indicateur11: '1%'
  max:
    indicateur3: '500'
    indicateur4: '500'
    indicateur5: '500'
    indicateur6: '45'
    indicateur7: '45'
    indicateur8: '45'
    indicateur9: '100%'
    indicateur10: '0%'
    indicateur11: '0%'
production:
  http:
    port: 3000
  mailer:
    service: 'Gmail'
    user: 'username@gmail.com'
    password: 'password'
    fromUser: 'ME ✔ <username@gmail.com'
    toUserOK: 'username@gmail.com'
    toUserKO: 'username@gmail.com'
    sujectMailOK: ' Les indicateurs du {0} sont disponibles'
    sujectMailKO: ' Un problème a eu lieu lors de la mise à jour des indicateurs'
  cron:
    time: '0 23 * * * *'
  shell:
    dirFile: 'exemples'
    sftpServer: '<sftp_username>@<sftp_id>'
  seuil:
    indicateur3: '400'
    indicateur4: '400'
    indicateur5: '400'
    indicateur6: '35'
    indicateur7: '35'
    indicateur8: '35'
    indicateur9: '98%'
    indicateur10: '2%'
    indicateur11: '1%'
  max:
    indicateur3: '500'
    indicateur4: '500'
    indicateur5: '500'
    indicateur6: '45'
    indicateur7: '45'
    indicateur8: '45'
    indicateur9: '100%'
    indicateur10: '0%'
    indicateur11: '0%'